// Generated by https://quicktype.io
// -- ==============================================   
// --  proyecto: 03-pokedex
// --  filex: sc_0\V20 01 njn Semilla.sql
// --  filex: src\seed\interfaces\poke-response.interface.ts
// --  ==============================================  

export interface PokeResponse {
    count:    number;
    next:     string;
    previous: null;
    results:  Result[];
}

export interface Result {
    name: string;
    url:  string;
}
